"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Aggregate.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'packages' : [ 'requests' ] }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)